// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtSR9MW24aBFn6gQRHZpqgnqrIDuC5Cjk',
    appId: '1:601426448842:web:e444c3fcb613a740f3bf33',
    messagingSenderId: '601426448842',
    projectId: 'abins-musthafa',
    authDomain: 'abins-musthafa.firebaseapp.com',
    storageBucket: 'abins-musthafa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpklkVzHnan0MCi9BbVm4UQGH7gjodt0g',
    appId: '1:601426448842:android:161507a078183fa6f3bf33',
    messagingSenderId: '601426448842',
    projectId: 'abins-musthafa',
    storageBucket: 'abins-musthafa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfHhGRxq0ElIkIXCkA37tj-PxmIxCtCPg',
    appId: '1:601426448842:ios:28e1ff3f77f024c9f3bf33',
    messagingSenderId: '601426448842',
    projectId: 'abins-musthafa',
    storageBucket: 'abins-musthafa.appspot.com',
    iosClientId: '601426448842-usjmcq5oud8aotqrfcsqnb2gs6dtf4jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeb',
  );
}
